#pragma once

//enum eNetworkResultCode
//{
//	eNRC_OK = 0,
//	eNRC_AUTHORITY_NOT_PERMIT,
//	eNRC_USER_PWD_NOT_MATCH_ERROR,
//	eNRC_MACHINE_EXISTS,
//	eNRC_MACHINE_NOT_EXISTS,
//	eNRC_REPORT_CODE_VERSION_NOT_MATCH,
//	eNRC_REPORT_CODE_SOCKET_AND_ID_NOT_MATCH,
//	eNRC_CURD_USER_EXISTS,
//	eNRC_CURD_USER_NOT_EXISTS,
//	eNRC_CURD_DB_FIND_ONE_ERROR,
//	eNRC_CURD_DB_INSERT_ERROR,
//	eNRC_CURD_DB_DELETE_ERROR,
//	eNRC_CURD_DB_EXCEPTION,
//	eNRC_CURD_DB_UPDATE_ERROR,
//	eNRC_CURD_MAX
//};

enum eCarGoAppSharedProtocolResult
{
	eCGASPR_OK = 0,
	eCGASPR_VERSION_NOT_MATCH,
	eCGASPR_VERSION_MAP_NAME_NOT_MATCH,
	eCGASPR_MAX
};