#pragma once


enum eCarGoAppNetworkMessage
{
	eCGANM_C2S_QUERY_DELIVER_POINT_CAR_INFORMATION,
	eCGANM_S2C_QUERY_DELIVER_POINT_CAR_INFORMATION_RESULT,
	//eCGANM_S2C_CAR_AT_DELIVER_POINT,
	//eCGANM_S2C_CAR_LEAVE_DELIVERPOINT,
	eCGANM_MAX,
};