#pragma once


enum eAskCarGoResultMessage
{
	eACGRM_OK = 0,
	eACGRM_NO_SUCH_HW_ID,
	eACGRM_LOST_CONNECTION,
	eACGRM_CAR_DRIVING,
	eACGRM_WAIT_CUSTOMER_FETCH_MEAL,
	eACGRM_CAR_WAITING_TRAFFIC,
	eACGRM_CAR_NOT_AT_POINT,//not expected car node ID
	eACGRM_ASK_TO_GO_AGAIN,
	eACGRM_ASK_TO_GO_DATA_IS_NOT_CORRECT,
	eACGRM_OUT_OF_CONTROL,//some object is not exists(nullptr)
	eACGRM_MAX
};