#pragma once


enum eAskCarGoResultMessage
{
	eACGRM_OK = 0,
	eACGRM_NO_SUCH_HW_ID,
	eACGRM_LOST_CONNECTION,
	eACGRM_CAR_DRIVING,
	eACGRM_WAIT_CUSTOMER_FETCH_MEAL,
	eACGRM_CAR_WAITING_TRAFFIC,
	//eACGRM_WAIT_CAR_SINGNAL_,
	eACGRM_MAX
};